# Generated by Django 4.1.4 on 2022-12-11 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers_service_area', '0002_servicearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='providers_service_area.provider'),
        ),
    ]
