# Generated by Django 4.1.4 on 2025-11-21 00:40

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=250,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Non-valid Phone Number",
                                regex="^\\+?\\d{8,17}$",
                            )
                        ],
                    ),
                ),
                ("language", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("area", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="providers.provider",
                    ),
                ),
            ],
        ),
    ]
